// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl-Xb5d9J2t-gYiFl5eYRqGmznmC1_Ws4',
    appId: '1:720601743004:web:af0769fa23386c1f7cf759',
    messagingSenderId: '720601743004',
    projectId: 'catalogoaragon',
    authDomain: 'catalogoaragon.firebaseapp.com',
    storageBucket: 'catalogoaragon.firebasestorage.app',
    measurementId: 'G-2YGMWP08VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRZLK1Nu0cYPGdFmyZHmobPuJDAqS64lo',
    appId: '1:720601743004:android:ce35e7733a0bf5117cf759',
    messagingSenderId: '720601743004',
    projectId: 'catalogoaragon',
    storageBucket: 'catalogoaragon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT3lgCzkGTnoobayNbPYSZMK9wckvLZMI',
    appId: '1:720601743004:ios:afc8a4cf56bd3efb7cf759',
    messagingSenderId: '720601743004',
    projectId: 'catalogoaragon',
    storageBucket: 'catalogoaragon.firebasestorage.app',
    iosBundleId: 'com.example.catalogo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT3lgCzkGTnoobayNbPYSZMK9wckvLZMI',
    appId: '1:720601743004:ios:afc8a4cf56bd3efb7cf759',
    messagingSenderId: '720601743004',
    projectId: 'catalogoaragon',
    storageBucket: 'catalogoaragon.firebasestorage.app',
    iosBundleId: 'com.example.catalogo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl-Xb5d9J2t-gYiFl5eYRqGmznmC1_Ws4',
    appId: '1:720601743004:web:522f7eeac373a7727cf759',
    messagingSenderId: '720601743004',
    projectId: 'catalogoaragon',
    authDomain: 'catalogoaragon.firebaseapp.com',
    storageBucket: 'catalogoaragon.firebasestorage.app',
    measurementId: 'G-NBWY0CXBY7',
  );
}
